Repository ml6team/fondant, pull requests merged in 2023-05, with the labels that each got.

#54 Load subset into dataframe
  fondant/dataset.py
  pyproject.toml
  tests/example_data/components/1.yaml
  tests/example_data/manifest.json
  tests/example_data/raw/split.py
  tests/example_data/raw/testset.parquet
  tests/example_data/subsets/index/part.0.parquet
  tests/example_data/subsets/properties/part.0.parquet
  tests/example_data/subsets/types/part.0.parquet
  tests/test_dataset.py
Labels: Core

#65 Remove outdated docs assets
  docs/class-hierarchy.png
  docs/data-flow.png
  docs/fondant_internals.md
  docs/kubeflow_101.md
  docs/manifest_example.png
Labels: documentation

#77 Run black on tests and all examples
  .pre-commit-config.yaml
  examples/pipelines/config.py
  examples/pipelines/finetune_stable_diffusion/components/clip_downloader_component/src/main.py
  examples/pipelines/finetune_stable_diffusion/components/clip_downloader_component/src/utils/image_downloader.py
  examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/main.py
  examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/embedding_utils.py
  examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/knn_service.py
  examples/pipelines/finetune_stable_diffusion/components/clip_retrieval_component/src/utils/timer.py
  examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/main.py
  examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/utils/blip_model.py
  examples/pipelines/finetune_stable_diffusion/components/image_caption_component/src/utils/image_captioning.py
  examples/pipelines/finetune_stable_diffusion/components/image_conversion_component/src/main.py
  examples/pipelines/finetune_stable_diffusion/components/image_conversion_component/src/utils/img_conversion.py
  examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/main.py
  examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/train_text_to_image.py
  examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/utils/dataset_utils.py
  examples/pipelines/finetune_stable_diffusion/components/sd_finetuning_component/src/utils/training_utils.py
  examples/pipelines/finetune_stable_diffusion/config/general_config.py
  examples/pipelines/finetune_stable_diffusion/sd_finetuning_pipeline.py
  examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
  examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
  examples/pipelines/simple_pipeline/config/general_config.py
  examples/pipelines/simple_pipeline/simple_pipeline.py
  tests/test_component.py
  tests/test_component_specs.py
  tests/test_dataset.py
  tests/test_import_utils.py
  tests/test_logger.py
  tests/test_manifest.py
  tests/test_manifest_evolution.py
Labels: CI/CD

#78 Update simple pipeline components to use new interface
  examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
  examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
Labels: Components

#105 update subset write location
  fondant/manifest.py
  tests/example_specs/evolution_examples/1/output_manifest.json
  tests/example_specs/evolution_examples/2/output_manifest.json
  tests/example_specs/evolution_examples/3/output_manifest.json
  tests/example_specs/evolution_examples/4/output_manifest.json
  tests/example_specs/evolution_examples/5/output_manifest.json
  tests/example_specs/evolution_examples/6/output_manifest.json
  tests/example_specs/evolution_examples/7/output_manifest.json
  tests/example_specs/evolution_examples/8/output_manifest.json
  tests/example_specs/evolution_examples/input_manifest.json
  tests/test_manifest.py
Labels: Core

#103 Add manifest documentation
  docs/manifest.md
  mkdocs.yml
Labels: documentation

#108 Handle kfp types
  examples/pipelines/simple_pipeline/components/load_from_hub/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/load_from_hub/requirements.txt
  examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
  fondant/component_spec.py
Labels: Core

#34 Implement Fondant pipeline class
  .github/workflows/pipeline.yaml
  examples/pipelines/controlnet-interior-design/config/general_config.py
  examples/pipelines/pipeline_configs.py
  examples/pipelines/simple_pipeline/components/embedding/src/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/image_filtering/Dockerfile
  examples/pipelines/simple_pipeline/components/image_filtering/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
  examples/pipelines/simple_pipeline/components/load_from_hub/Dockerfile
  examples/pipelines/simple_pipeline/components/load_from_hub/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
  examples/pipelines/simple_pipeline/config/components_config.py
  examples/pipelines/simple_pipeline/config/general_config.py
  examples/pipelines/simple_pipeline/simple_pipeline_fondant.py
  fondant/component.py
  fondant/component_spec.py
  fondant/data_io.py
  fondant/exceptions.py
  fondant/manifest.py
  fondant/pipeline.py
  fondant/pipeline_utils.py
  tests/example_pipelines/invalid_pipeline/example_1/first_component.yaml
  tests/example_pipelines/invalid_pipeline/example_1/second_component.yaml
  tests/example_pipelines/invalid_pipeline/example_2/first_component.yaml
  tests/example_pipelines/invalid_pipeline/example_2/second_component.yaml
  tests/example_pipelines/valid_pipeline/example_1/first_component.yaml
  tests/example_pipelines/valid_pipeline/example_1/second_component.yaml
  tests/example_pipelines/valid_pipeline/example_1/third_component.yaml
  tests/example_specs/component_specs/kubeflow_component.yaml
  tests/test_manifest.py
  tests/test_pipeline.py
Labels: Core

#140 [Alpha pipeline] Write to hub component
  examples/pipelines/simple_pipeline/components/load_from_hub/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/write_to_hub/Dockerfile
  examples/pipelines/simple_pipeline/components/write_to_hub/__init__.py
  examples/pipelines/simple_pipeline/components/write_to_hub/fondant_component.yaml
  examples/pipelines/simple_pipeline/components/write_to_hub/requirements.txt
  examples/pipelines/simple_pipeline/components/write_to_hub/src/main.py
  examples/pipelines/simple_pipeline/pipeline.py
Labels: Components

#152 Add embedding based LAION retrieval component
  examples/pipelines/finetune_stable_diffusion/components/embedding/src/fondant_component.yaml
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/Dockerfile
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/fondant_component.yaml
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/requirements.txt
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/src/__init__.py
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/src/clip_client.py
  examples/pipelines/finetune_stable_diffusion/components/embedding_based_laion_retrieval/src/main.py
Labels: Components
