Repository ml6team/fondant, pull requests merged in 2023-04, with the labels that each got.

#48 split fondant component into load and transform
  examples/pipelines/simple_pipeline/components/image_filtering/src/main.py
  examples/pipelines/simple_pipeline/components/load_from_hub/src/main.py
  fondant/component.py
  fondant/components/__init__.py
  fondant/components/common.py
  fondant/components/hf_datasets_components.py
  fondant/components/pandas_components.py
  fondant/dataset.py
Labels: Core

#50 Add typing check
  .pre-commit-config.yaml
  fondant/component_spec.py
  fondant/dataset.py
  fondant/manifest.py
  fondant/schema.py
Labels: CI/CD

#29 Host documentation
  README.md
  docs/.readthedocs.yaml
  docs/fondant_internals.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
Labels: documentation
